# Inferring mRNA from Protein

# Given: A protein string of length at most 1000 aa.
# Return: The total number of different RNA strings from which the protein could have been translated, modulo 1,000,000. (Don't neglect the importance of the stop codon in protein translation.)

data = 'MDMWINKFEHGEMCSALCWVEHYHARIQRDHMASVAYKKRHEQGQKFEEMKPANVQFPEFCETLGMCTVCHTVGSCDNHEVALLIWCRYTPQLQKAMWCSFYPPQHCHKGYCPVYKLHARICVVVMGYGEHTRMVDTSGVTNCRESGTCKNWLWQEHEDSGESANMSCGKDQRRAEFIQLQAHRMCFKGLPIGGKQPMMEINFSVTEYRIHMWIIIWEGQQVRTAVLSGGRKEASVGEGSMSYISVIFDTPMHLDGIWICADQTLSGQLCLYHAHAMYMEKKLDDNKLKTHCYGNFVTPCATKQMKWGIKDSSAKEMDECAVRECKFRCCCRRGTLKLRFYCYMVTLEWMKIGIIQIAWKMFYQRTEPKAGHWAKAGQIGHADQLGCASNTAMEEFPQVKIPDGNHWRPLWMRCSCIVSPLIQKFDCRYRSSFDPCVGDDSWWRTHCCNGRTLCCHSDMKKYQWHHNPGHVWLKTCWMMMQADGDKNKPHLWSNHYWEVAIKNKYSAQQMAKGPLLYWAGSTAIEAIECMCYKVNQQPVTSIIPFEFFFARNRGWVWIWHMRITGQTSPYEVPWGNVSRRWICELQYYCVGTNWIVAFLTNDTNNEIHMETIPYTYGYHCRNIFYMGDYDGHSPANGVTFASDCQHSYDHHTMRHFDWLAELMKPQIDMMETMCESFVYINCGIEFDKESVKDFNQSYQPLIYFWVVVSSAEGSGPQRILCKTNWLPEAKSKYRTTDRTNRAERGPFYGRIEMDISKPKFTCNRVFHFITFKLVPHWFLNAWCFLLLIEHTECSAYHESKEIGNGSHNGRRITMWFVNYPCEMGQEQRIMRGEACHMECCLRNNQQEKQQKDHQDERVWVTLVMHAPFTNDTREEPYDSGVINVPFPVVTWNDTNYRMGVQMWQSTDDATEEEPMVADAQYPEDHRYSNYPCILESSGQWPDPVTECWFAAGWHVFDTLMQYKAIFPTMYIQDDHSPYLTTWFQMFFYFRRFEMYYGSWM';

a_to_c = {
	'F': 2, 'L': 6, 'I': 3, 'V': 4, 'M': 1, 'S': 6, 'P': 4, 'T': 4, 'A': 4, 'Y': 2, 'H': 2, 'N': 2, 'D': 2, 'Q': 2, 'K': 2, 'E': 2, 'C': 2, 'R': 6, 'G': 4, 'W': 1
}

result = 1
for n in data: result = (result * a_to_c[n]) % 1000000

print(result*3)