# Complementing a Strand of DNA

# Given: A DNA string s of length at most 1000 bp.
# Return: The reverse complement sc of s.

first = 'GATTGGGCAAGCGGGTTCATCCGAGGACTCAGCCTGTTACGATAGCTACTGCGAATAAGGCCTTCCAACGAACTGGAAATCGGGGTGTGGATTGGCCCTGAGCCAAGGTACAGCACCGTGCTGTGGACTCTTCCGAGTTAGGAGCCACTCACAACATAGATTGGAAAAGGCGCGCCCAAATCACGCATTCAGCTACAACAGAATGTAGGAGCGGCGACATTGCGACGAACCGCCGGCGTAGGTGATGAAAGCGGAACACAGGCGCTCGCAAGCTGACGGGGGGGAGATACTAGAGGTCCAAGCAGTCCGCTTGACCAACGAGTGCTTAGCAGTCCAGACTGGGCTCGGGGCTCTTCTTTAGCTTCCTATCAAGCTCGTGACATTACCTCCTCGCGTCGGTACAAAGGTTCTACCCTCGAACACGTATTGACCGAATTGTTGGAGAAATAGGGCGATTTAAGTATAGTCGTTTGTCTGTAAGACTTGACTTTCATGGGACACCAGTAACAAACGAGACTGATATGTACCTATCGGCAAGTCCTGTCCGGGATCCGATGAACGGTTGTCCCTCGACGGCTGAGGACAAGCTTATATTGGCAAGCGGGAGTGTACGTTCTGAAATATGTTAAATTAGCTTGCAGGGTTGTGTCCGCGGATACCGTGGTATATGGGTTCCGTTGTAAACTGGACAGGGTGTTGCGACGCTCACGCTCTACTGGATTGAAGACGTCGCACCAACTTTGGATATTGATCTGAATGGGGGTGACTCGTGATACATACTACCCGGACTTGCGGCAACCGGTGGTGGATCTACCCCA'
second = ''

for nt in first:
	match nt:
		case 'A':
			second += 'T'
		case 'G':
			second += 'C'
		case 'C':
			second += 'G'
		case 'T':
			second += 'A'

print(second[::-1])